# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Test Workflow

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      
      - name: pnpm version
        run: pnpm --version